### ISSUE TITLE
[init]破题

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/S09E05gDAMA#1]
~ 关联: [[init.]如何进入和合阵地?](https://github.com/GC4WP/S07E15gDAMA/issues/1) /[[TUV]Github 实效使用方法集锦](https://github.com/GC4WP/S07E15gDAMA/issues/4)/[[TUV] 理解和合](https://github.com/GC4WP/S07E15gDAMA/issues/3)

@GC4WP/zq4s07e15 

## 题面儿

- 保持上次小组的编队
- 将《共产党宣言》的部分内容
- 改编成一篇800字以下的文章
- 体材不限（诗歌，散文，小说，戏剧皆可）
- 要求提交同一内容的两个版本作业：
    1. 书面版
    2. 语音版

作业要求，不用说，大家也知道了。

    平易雅洁，琅琅上口

## 试破

- `共宣` 是特殊应用文, 是纲领性文献
- 改编姿势,一般也就:
    + 虚构写作:
        * 小说 --> 800 字是 Nature 专栏要求太难
        * 散文 --> 800 字太短,来不及聚神
        * 诗歌 --> 咳...
    + 非虚构写作:
        * 说明文 --> 没理解透彻呢...
        * 书信 --> 给谁?
        * 电信 --> 通电给谁?
        * 新闻 --> 不新了
        * ...
- 好象都嗯哼了?!反向思考:
    + 立其诚 <-- 什么最感动了自己,就扼住怼成篇吧...
    + ...

## 嗯哼
~ 大家回复 Issue 先绘出文字版本的理解, Zoom 会议时好针对性的合并同类...
完成回复的 点亮 chk-box 呗:

- [ ] @anxinzhu 026-上海-安心竹 
- [ ] @BrookSongBrookSong 029-香港-宋偲瑄
- [ ] @expressseven 253-上海-申小七
- [ ] @sallysong007 193—天津—海岸线
- [x] @ZoomQuiet 057-珠海-Zoom,Quiet

**Comment by anxinzhu** [comment]
诗歌后面的咳…是怎样…

**Comment by sallysong007** [comment]
看完共宣1-2章，我的感受就像佩老师教授的那样，共宣就是符合教理模式的问答和慷慨激昂的雄辩。给我的直观感受就是一问一答引领读者进入一个氛围里，并根据它的逻辑深信不疑。
所以我想到，如果用类似一问一答的模式写出我想对资本主义的理解和感受，大概就是我的立其诚了。

**Comment by expressseven** [comment]
最近太忙，刚刚进入Github和合组看文档，加油看  共产党宣言

**Comment by sallysong007** [comment]
S09E05d1 和合会议纪要:
日期：03/20
人员：大妈、小宋、竹子、海岸线、申小七
会议形式：微信语音+文字
完成四项议题
### 议题一：利用共同音频投放账号发布对本次作业的文章通读。
**形成决议1：大妈为大家申请了小组音频平台。**
本期通读音频均需放置：荔枝音频
1、登录荔枝FM录制 音频后
2、搜索 ZoomQuiet 加好友
3、投稿FM2193128
**形成决议2：大妈负责为王佩老师申请一个公共投稿音频平台，以便老师顺利收听声音版作业。**

### 议题二：通读三篇已交的始稿，并进行全员投票，票选出一篇文章代表小组，全力和合打磨。
其中

> 大妈观点：
> 投票前，应该先通读，不然只过眼不过嗓难入心。

>  小宋观点：因为不是所有作品都有诵读的价值，入眼自然入心，何必形式化严重？怎么学习写作? 根基就是背，诵经典。和合就是一个意见和评论汇总的机制，它是根据大家的意见，完善细节的过程。但和合能不能从根本上提高写作能力?并不能，治标不治本，可能提高一下表达能力，但文学根基，不是和合出来的，是自己大量阅读，背诵，积淀的结果。
> 文学的本质就是阅读经典，吸取文气。体察生活，升华认知。没那么复杂。所有的技巧，都是为了获取经典的本源。只有真正的经典，才值得诵读以入心。
> 以及，文学修养不是体现在，最好的文章写的有多好，而是体现在，自我屏蔽烂用词和烂文章。作家之耳就是，我知道这东西烂，故有底线，自动筛选，不让烂文字涌现。即，写字讲究格调，不是什么都好意思往自己名下放。

> 大妈观点：同意小宋的观点。和合一时半会不会提高每个人的中文水平。和合的意义更多在于通过读和怼。把自己积累下的，可能好的那一点中文感觉挤出来或提炼出来。这是平日看自己文章所无法达成的，只有看别人文章或专注某篇时才容易把自己的积累具现化出来。
> 同时，大妈认为提高中文能力的确是应该多读经典、多背、积累、沉淀，我们拥有比古人多得多的知识和资讯量，通过好中文这个课，可以帮助我们将这些积累转化出来，形成自己的好文章。
> 此处，未形成决议。但再次凸显出：微信交流的信息碎片化。
> 大妈感慨：所以 zoom.us 能有个完备的讨论共识过程…微信一分钟短语音…难以陈述完备…对发言…收听…理解…线索…都难…

### 议题三：语音投票

> 宋：选竹子那篇。喜欢她类似《疑问集》这种表达形式。聂鲁达用短句来表达对世界刨根究底地，往往以天真的思索来颠覆我们对世界本源的认知。用这个形式来嵌套共宣里新势力击破旧势力，形式是可以应用的。海岸线的《快乐王子》虽构思精巧，但离题稍远，也不符合共宣的磅礴文气。大妈那篇打油诗，文气也不够气势磅礴。

> 大妈：选自己。自己这版虽呆板，但尽力基本表现了共宣的全部内容。我想还原成解放区儿歌形式的《共宣》。由于紧扣共宣内容才应该是作业最大的坑，因此，坚持选自己这篇。

> 海岸线：喜欢竹子那篇，画面描绘令人浮想联翩。大妈那篇读起来更像《共宣》，但对读者不够友好。
> 小七：赞成大妈。大妈的扣题很强，唯一不适感就是感觉回到了文化大革命时代。

> 竹子：投自己的。王佩老师要语音的，所以五个人可以轮流读，更好听些。

第二轮发言：

> 小宋：直觉上喜欢竹子的，但大妈教会大家很多，劳苦功高，大妈也坚持自己的，理应得偿所愿。且大妈的进步空间很大，因此建议怼大妈。

其他人均附议。
**形成决议：竹子的文章因为太好而被弃用，可在发布完本次作业后，再行发布。剩下的时间，大家尽可能多怼。**
### 议题四：决定后几天和合流程

**形成决议每日:**
1. 至少和合一个版本
2. 定期会议 
3. 所有版本通读感应
PS:

> 小7/大妈 常常有事在身无法参加会议
> (可尝试用荔枝FM 录制后投稿FM2193128 先搜索 ZoomQuiet 加好友)
> 以便分布移动嗯哼…

**Comment by expressseven** [comment]
今天怼了一把大妈的《共宣歌》，自己把自己怼废了，当一篇打油诗无怼可怼是让人高兴呢？！还是让人深思呢？

为啥感觉其他小伙伴都没怼呢？

**Comment by ZoomQuiet** [comment]
DONE as good! 达成/归档/交付ed
