### ISSUE TITLE
[TUV]疑问体 共宣集

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/S09E05gDAMA#2]
## 背景

- 17.3.20 快速直觉投票
- 小组决定怼俺的打油诗体
- 渗 聂鲁达 的精魂, 将共宣磅礴的气势
- 变成平易的对话

## 方案

- `d1` 3.20 `始`稿
    + 1h ~ [4ca5ab0](https://github.com/GC4WP/S09E05gDAMA/commit/4ca5ab072eb590685dbc1ed135026214a801d475#diff-f79a64ac8dac64551b49540799f2698f)
- `d2` 3.21 初稿
    + 1h 微信群低烈度讨论, 明确策略
    + .5h Pivot --> [ff79013](https://github.com/GC4WP/S09E05gDAMA/commit/ff7901389ab0aa93735fd2addac093df3db3b822#diff-f79a64ac8dac64551b49540799f2698f)
- `d3` 3.22 再稿
    + .5h [9f3096f](https://github.com/GC4WP/S09E05gDAMA/commit/9f3096fc3623d3b1e9137005936b66829a610008#diff-f79a64ac8dac64551b49540799f2698f)
    + .1h 旁听...
- `d4` 3.23 稿3/4
    + .5h [6cab4a9](https://github.com/GC4WP/S09E05gDAMA/commit/6cab4a950fe1c4d3f93e39815b5169efb875ff49#diff-f79a64ac8dac64551b49540799f2698f)
    + 1h 旁听,记要
- `d5` 3.24 稿4
    + 1.5h 旁听,记要
    + .5h [bb8f7d7](https://github.com/GC4WP/S09E05gDAMA/commit/bb8f7d7a9875e9e2a8a42399dcca1198ba46ddf1#diff-f79a64ac8dac64551b49540799f2698f)
- `d6` 3.25 稿5
    + .5h [521707a](https://github.com/GC4WP/S09E05gDAMA/commit/521707a1b9fb8a2882525ce6bf86051175b8eb2d#diff-f79a64ac8dac64551b49540799f2698f)
- `d7` 3.26 定稿/录音 发布

## 复盘
~ 大家及时回复组织这次 和合的体验吧

完成回复的 点亮 chk-box 呗:

- [ ] @anxinzhu 026-上海-安心竹 
- [x] @BrookSongBrookSong 029-香港-宋偲瑄
- [ ] @expressseven 253-上海-申小七
- [x] @sallysong007 193—天津—海岸线
- [x] @ZoomQuiet 057-珠海-Zoom,Quiet

**Comment by ZoomQuiet** [comment]
## 和合技
参考: [S07E15g193: 嗯哼重来 - 简书](http://www.jianshu.com/p/04b10e675998)

`C-C` 点评的姿势, 其实也应该慢慢规范起来的
## 和合点评

- 目标是更好的文字, 而不是抖机灵
- 和罗规的民主发言一样:
    0. 声明态度, 同意/不同意
    1. 给出理由
    2. 给出方案
- 和微信 主妇流 一样
    + 点评是可以修订的, 不要对话, 要完备的阐述所有观点
    + 怼的具体那一行就是我们讨论的主题
    + 不应该跨行怼, 如果实在需要, 请在点评中

> 引用另外一行

并给出完整的建议...

PS:

- 要知, 可以批量导出所有点评的
- 俺展示给大家看过 隔壁 怼 共宣时,各种点评的文字
- 所以, 点评也是写作 微而完备的议论文
- 所以, 和合技 包含的关联又实用的细节是无穷的,
- 唯一的限制只有我们的耐心

@GC4WP/zq4s07e15

**Comment by anxinzhu** [comment]
# S09E05d3 和合会议纪要:
日期：03/22
主持：小宋
人员：大妈、小宋、海岸线、安心竹
会议形式：zoom+文字


完成四项议题
## 议题一：三人每人一段轮流朗读大妈的初稿《自由问》

## 议题二：讨论文体
- 安心竹：看不出用的是什么文体，有点像政治课的问答题。
- 宋：运用设问的形式，对共产党宣言进行提炼，更加清晰。
- 海岸线：对 ，而且更有气势。

## 议题三：个人对共产党宣言有什么印象深刻的地方。
- 宋：暂时在研究英文版。
- 海岸线：生产力和生产关系的矛盾。当资产阶级打败封建阶级的时候，它暂时解决了这个矛盾。但是像一个魔法师制造了一个生产关系怪兽，现在已经无法掌控。
- 安心竹：点评了，还没有写下来，再尝试。

## 议题四：怼《自由问》
### 文章第一段 
- 宋：关于自由，有一种说法，自由不是你想做什么就可以做什么，而是你想不做什么就可以不做。第一段文字上可以表达得直接人心。例如，学习是灵魂的需要。
- 海岸线：劳动像呼吸一样自然。
- 安心竹：劳动不是被迫的。
- 大妈：共产主义社会 不仅仅是社会结构 而是生产力足够强大到支撑所有人的自在发展, 以及每个人的精神也足够提升到不追求低级的生理享受了....

### 第二段及第三段 
- 宋：全体的自由，可以用巴别塔的典故。
- 大妈：这是基于第二章最后一句的理解写出的三段。就是这句：代替那存在着阶级和阶级对立的资产阶级旧社会的，将是这样一个联合体，在那里，每个人的自由发展是一切人的自由发展的条件。
- 安心竹：第三段我与大妈理解的不同，大妈写的意思是个体是自由联合起来而不是被迫联合。我的理解是，个人的自由发展是一个前提，旧的联合体即资产阶级社会，工人们的发展，包括劳动，学习，等都不是自主的选择，但在新的联合体，个人的自由发展是全体自由发展的基础条件，那么就是说，在新的联合体中，个人的自由发展会得到保证。
- 宋：你的意思是说，大妈的角度是那种联合方式的自由性，你的角度是，个体自由是全体自由的基础，对吗？
- 安心竹：我觉得这句话从文字上理解是这个意思。
- 宋：第三段开头感觉需要更实质的内容，自由的联合，联合的自由，有点儿表达不是很清晰。
- 海岸线：我能看懂，一起开拓未来，没有国家和民族，只是不太清楚接下来改动的方向。
- 宋：不太清楚自由地联合这句话的具体意思，具体是什么在发展。
- 安心竹：我认为自由与发展都是重要的。
- 宋：自由的意思比较模糊。我们把能想到的都录下来，然后整理思路。这句话的理解，一个有自由意识的群体取决于每一个个体的自主，而不是局限于阶级的固化。比如教育方面，上不上国际学校取决于你的经济局限，并不是自己的意识选择。所以我认为共产主义社会，所有的选择必须是自主的，而不是局限于经济等。
- 安心竹：按需分配对吗
- 宋：对。需的前提是独立的人格。自由的前提也是独立。
- 海岸线：对的，我的需要是我的独立思想，只有独立才不依赖于物质和其他人的想法。
- 宋：需的前提是独立人格，顺从内心的召唤，而不局限于外在物质，政策，或者社会强加于我们的观念。共产主义社会的分配方式给我们提供了可以顺从内心去做选择的前提。
有两个循环：
- 物质发展》思想境界提升》乐于劳动》物质更丰盈
- 思想境界提升》独立人格》自知需求》利用自由的权利》基于物质丰富
- 安心竹：有一个疑问，为何共产主义理想对他们的物质会极大丰盈如此自信，以至于可以实现按需分配。
- 大妈：这种自信来自资本主义社会的发展观察，因为在资产阶级的压迫下, 都已经爆发了这么大的生产力，要是没有了压迫, 全心发展, 更加嗯哼。
- 海岸海：我觉得大妈是推导出来的，资产阶级打败封建阶级，变得更好，所以无产阶级更厉害。
- 宋：我认为这个逻辑站不住脚
- 大妈：这是一个自然的推论....因为资本主义社会中, 所有生产都是无产阶级干出来的哪，又不是资本自己生产出来的，资本只是润滑剂....以及生产资料的极大利用, 而没有资本主义/社会主义 阶段的各种其它理由的消耗。只有资产阶级才能创造出无产阶级，因为只有这样才能创造出更多的财富，同时也令无产阶级越来越强大。
- 安心竹：我们国家是社会主义社会
- 海岸线：我们跳过了资本主义社会
- 大妈：社会主义社会和共产主义社会，从社会结构上并无差别，最大的差别而是动力/理由。
- 宋：是不是它想说共产主义是资本主义的极端形态，是资本主义发展到一定阶段的产物。当社会资本更强大时，创造社会财富的无产阶级必然更强大，从而推翻资产阶级。然后它默认共产主义社会每个人的思想境界很高，每个人都热爱劳动，所以物质会更丰盈，可以按需分配。
- 安心竹：但是资本家也是人，无产阶级也是人，为什么思想境界就高了呢？
-  大妈：劳动改造人类哪。
- 安心竹：劳动可以改造人类吗？劳动只能改变技术，可以改变人类的境界吗？从古自今，人类的罪性一直都在。
- 宋：无产阶级一直在劳动，资产阶级一直好吃懒做，所以无产阶级思想境界高。
- 安心竹：但无产阶级是被迫的。
- 海岸线：那其实劳动一直是被迫的。
- 宋：我们的会议要结束了，我们可以思考这些问题。
1.什么是自由，什么是自由发展，什么是全体的自由发展，有什么关系
2 共产主义社会为何物质会丰盈
3 共产主义社会为何人的境界更高。


会后任务：
S09E05d3 和合完成:
媒体资料在:
http://t.cn/R6qfGen
请@026-上海-安心竹 轮值书记到
[TUV]疑问体 共宣集 #2 Issue

任务:
1. 根据录音精神认真怼:
v2(TUV) 和合d3 BC 成果
http://t.cn/R6bD5gF
2. 各自至少增补一则共宣问, 来包含自己对共宣最有共鸣的一点
3. 俺将尽力在明天 12:00 给出 BC版 v3 所以, 抓紧…

协同规约每日:
1. 至少和合一个版本
2. 定期会议 
3. 所有版本通读感召和合

**Comment by ZoomQuiet** [comment]
@GC4WP/zq4s07e15 
## 17.3.23 独怼记要

今天神奇的大家都各自有事儿, 无法按时进入会议室怼,
所以, 忽悠:`@026-上海-安心竹`

软件工程中的小黄鸭调试方法,
zoom.us 打开, 开始录音,
拿个自己喜欢的玩偶当对话对象

- 读一段文稿
- 自己说出感觉,分析一下问题
- 给出对策
- 下一段

以上, 20分钟, 搞完, 就有10个以上的点子来 C-C 了

然后,真的这么嗯哼起来了! ~ [GC4-026-d3e2m-audio_only_1_dui](https://www.lizhi.fm/2193128/2592118241498893318)

## 坑王
佩哥哥布置的各种作业,从来没有简单的, 都包含了很多坑,
这次的真的是坑王了:

  将《共产党宣言》的部分内容
  改编成一篇800字以下的文章
  体材不限（诗歌，散文，小说，戏剧皆可）

- 所谓改编,当然要在原作理解上的改编
- 否则, 俺改个常娥奔月的故事, 硬说是 共宣 相关的,太闹了...
- 问题是:
  + 共宣 本身内容就异常丰富
    * 包含了 Max 近20年研究的所有成果
    * 而120多年后, 共宣早已被反复消解/再解释无数次了
    * 所有涉及的概念 都可能失去了原作的指义
    * 外国甚至于有专门研究 共宣 这一文本后续相关版本演变历史和原因的科研项目和论文
  + 就我们这几天想正确理解 是不现实的
  + 那么整体理解不能时时, 部分的理解也自然不可能了
  + 也就是说, 我们只能拿 共宣 部分内部的偏见来改编
  + 立其诚 已破戒了, 因为自己都知道是偏见了
  + 好在平易 也没什么希望了, 因为自己都理解不能的东西, 不可能平易之
  + 悦耳 这可能是唯一有希望作到的:
    * 将一个无法真正理解的文本的部分
    * 改编成意义不明的文稿
    * 却要作到悦耳
    * 耳也通心 不傻...

举例说明, 共宣中的一句, 对俺很有感觉:

- In place of the old bourgeois society with its classes and class conflicts there will be an association in which the free development of each is the condition for the free development of all.
- 代替那存在着阶级和阶级对立的资产阶级旧社会的， 将是这样一个联合体， 在那里， 每个人的自由发展是一切人的自由发展的条件。

1996版 共宣中英对照的核心句... 当前俺的程序化理解是:

                 
    support <- make <-+
      |               |
      |       pFD -> Dev. -> person -+
      |        |              ^      |
      |        V              |      |
      |   <-- for             |      |
      V  /                    |      |
     aFD -> all -> support ---+      |
             ^                       |
             +------ association ----+


- 其中:
    + pFD ~ personal Free Development
    + aFD ~ all Free Development


怎么办?

- 立其诚 ~ 将困惑/不理解 表述出来
- 好平易 ~ 避开模糊的概念,就怼具体的事儿?
- 悦耳 ~ 反复读,将不常见的字替换为常见的, 将难念出来的替换成好念的, 将...

**Comment by anxinzhu** [comment]
终于深深明白老顽童周伯通的厉害之处，自己和自己说话那可真需要功力。。

在 2017-03-23 23:47:49，"Zoom.Quiet" <notifications@github.com> 写道：


@GC4WP/zq4s07e15

17.3.23 独怼记要

今天神奇的大家都各自有事儿, 无法按时进入会议室怼,
所以, 忽悠:@026-上海-安心竹

软件工程中的小黄鸭调试方法,
zoom.us 打开, 开始录音,
拿个自己喜欢的玩偶当对话对象

读一段文稿
自己说出感觉,分析一下问题
给出对策
下一段

以上, 20分钟, 搞完, 就有10个以上的点子来 C-C 了

然后,真的这么嗯哼起来了! ~ GC4-026-d3e2m-audio_only_1_dui

坑王

佩哥哥布置的各种作业,从来没有简单的, 都包含了很多坑,
这次的真的是坑王了:

将《共产党宣言》的部分内容
改编成一篇800字以下的文章
体材不限（诗歌，散文，小说，戏剧皆可）

所谓改编,当然要在原作理解上的改编
否则, 俺改个常娥奔月的故事, 硬说是 共宣 相关的,太闹了...
问题是:
共宣 本身内容就异常丰富
包含了 Max 近20年研究的所有成果
而120多年后, 共宣早已被反复消解/再解释无数次了
所有涉及的概念 都可能失去了原作的指义
外国甚至于有专门研究 共宣 这一文本后续相关版本演变历史和原因的科研项目和论文
就我们这几天想正确理解 是不现实的
那么整体理解不能时时, 部分的理解也自然不可能了
也就是说, 我们只能拿 共宣 部分内部的偏见来改编
立其诚 已破戒了, 因为自己都知道是偏见了
好在平易 也没什么希望了, 因为自己都理解不能的东西, 不可能平易之
悦耳 这可能是唯一有希望作到的:
将一个无法真正理解的文本的部分
改编成意义不明的文稿
却要作到悦耳
耳也通心 不傻...

举例说明, 共宣中的一句, 对俺很有感觉:

In place of the old bourgeois society with its classes and class conflicts there will be an association in which the free development of each is the condition for the free development of all.
代替那存在着阶级和阶级对立的资产阶级旧社会的， 将是这样一个联合体， 在那里， 每个人的自由发展是一切人的自由发展的条件。

1996版 共宣中英对照的核心句... 当前俺的程序化理解是:

support <- make <-+
  |               |
  |       pFD -> Dev. -> person -+
  |        |              ^      |
  |        V              |      |
  |   <-- for             |      |
  V  /                    |      |
 aFD -> all -> support ---+      |
         ^                       |
         +------ association ----+

其中:
pFD ~ personal Free Development
aFD ~ all Free Development

怎么办?

立其诚 ~ 将困惑/不理解 表述出来
好平易 ~ 避开模糊的概念,就怼具体的事儿?
悦耳 ~ 反复读,将不常见的字替换为常见的, 将难念出来的替换成好念的, 将...

**Comment by anxinzhu** [comment]
终于深深明白了老顽童周伯通的厉害之处，自己和自己说话那真是需要功力的。。

**Comment by ZoomQuiet** [comment]
@anxinzhu 是也乎,(￣▽￣)

- 自怼就是写作过程哪
    + 只是写出来可以用时间慢慢挤
    + 说, 就只能下意识的第一选择了
    + 反而总是能越过理智说出心里话
    + 所谓酒后吐真言 也是这个意思
- 当然, 也是能上写作技法的
    + 俺一般是先手写个草稿,思维导图式的
    + 先过一下, 自己想说的点之间的关系
    + 看哪个顺序有逻辑/线索/直观...
    + 其实, 拉清单/提纲的过程, 就已经头脑中反复说几次了
    + 然后, 自己对着图谱来说, 就容易不漏不乱不忘了...


![wechatimg8](https://cloud.githubusercontent.com/assets/22494/24295207/a205c4f2-10d4-11e7-9ac2-0cd323a939d9.jpeg)

**Comment by ZoomQuiet** [comment]
## 自由问自疏
~ 尝试记录和合过程中偏见的激荡

**S09E05** 作业要求改编共宣为 800 字以内的文章

当时全体就感受到一万点`无助`:

- 再次时隔多年接触到两个多甲子前的雄文
- 虽然意境感受的到, 但是,具体内容越读越模糊
- 其中嵌入的概念迭代是越品越多
- 想整体改编是不可能的
- 所以, 只能抓住自己最有感觉的一个点来尝试展开
- 只求将我们的偏见能和合出足够通畅的文字就已是成功

共宣1万多字,四章:

- 第一章: 说来由, 论述了阶级斗争和资产/无产阶级 的对立形成
- 第二章: 说共党, 描述共产党要作什么
- 第三章: 说文献, 再回顾历史挖掘共产主义的各种来由
- 第四章: 说计划, 定义口号和命运方向

第二章 最后一句承前启后, 非常有感觉, 所以,决心怼:

> 代替那存在着阶级和阶级对立的资产阶级旧社会的， 将是这样一个联合体， 在那里， 每个人的自由发展是一切人的自由发展的条件

中英对照这个核心句...程序化理解是:

                 
    support <- make <-+
      |               |
      |       pFD -> Dev. -> person -+
      |        |              ^      |
      |        V              |      |
      |   <-- for             |      |
      V  /                    |      |
     aFD -> all -> support ---+      |
             ^                       |
             +------ association ----+


其中:

+ pFD ~ personal Free Development
+ aFD ~ all Free Development

进一步溯源时又发现原文含坑:

> In place of the old bourgeois society with its classes and class conflicts there will be an association in which the free development of each is the condition for the free development of all.


    an association 
        in which 
            the free development 
                of each  <-- 每一个
    is the condition     <-- 不单纯是条件
        for 
            the free development 
                of all   <-- 全部每一个,而不是简单的整体

- 为什么用 `association` 而不是党/派/会社/... 之类?
- 为什么用 `condition` 而不是前题/需求/条件/要求/... 之类?
- 对这一断言的理解/设想/推导/遐想/... 就足以写出很多很多

029学员, 对此句的比喻是:

> 只有自证不缺钱，才能从银行借到钱，而有经济能力的人必不滥用那借贷。
> 只有内心渴望劳动，才能拥有随时不工作的自由，而渴望劳动的人必不滥用这自由

逻辑很自恰,但是, Max 构想的社会一定没有这么简单;

好叫你们知道:

那时 道德/劳动/工作/生活/自由/商品/产品/… 
一切我们熟知的概念都应该完全进化了...
相关的描述用词, 都包含了我们当前的局限性思维:

> 思想境界 

- 这词本身就带有价值取向时,才有意义
因为能分境界的, 必然得有评判标准,才能分高下
但那时 全员每个人的思想是高级一致的,无分高下,
每个人都自然而然的在自主追求自己的发展
并从内心第一选择整个人类发展需要的前沿领域
这时, 根本无道德之说了
因为所有人都已经在道中

> 无限自由 

- 这词也是法律界进行讨论的主体
对应的是法律限制下的有限自由
但那时 全员每个人的资源/追求/第一需求 是相同的
可以强行理解为高度限制下的无自由
因为每个人的自由选择和全体的一致了
再没有纷挠的自由意识
有点儿象 berg 种族 全体即个人 只是没有女王来掌握最终决议
从外界来看 每个人是没有任何自由的
但是,从内部来看, 每个人又是有无限自由的

> 热爱劳动 

- 热爱, 这定义本身也是价值倾向的
因为要对比逃避劳动...
问题是 这种描述无法回答为什么有的人热爱劳动, 有的却不?
但那时 劳动和工作已经和生活三位一体了
全员每个人都自然融入了全体持续发展的劳动中
没有爱或不爱
劳动就是生活日常的本身
象呼吸一样自然
我们只能爱上一种稀缺之物 对平常到已经无法感知到的事物
是无法论及是否爱的

> 工作的目的，理当是高尚和自由 

- 同前设想, 工作就是生活本身是没有目的的
所以, 也没有高尚/低下的差异了

> 只有内心渴望劳动，才能拥有随时不工作的自由，而渴望劳动的人必不滥用这自由

- 逻辑上的确是通的
但那时 已经没有劳动/工作/自由 的现在概念了
也就没有所谓滥用了...


几轮下来, 对 Max 当年以工程师的条理程序员的逻辑严密科学家的细致政治导师的磅礴气势
嗯哼出来的 `共宣` 其实:

- 就是篇科学幻想小说哪
- 用当时的一些概念, 净解重构成完全不同的概念,并立即用其构筑全新的社会图景
- 但是, 当我们不自主的去用自己的经验来脑补出所有细节时
- 过程中就自己说服了自己: `共产主义革命一定能胜利`
- 这就是发动每个人内心的模因来为作者工作的至高话术了...


### BGM
~ 作业还有一层坑在,要求同时提供作业的语音版本

既然有了语音, 那么配上吻合心境的音乐作为背景也是自然的选择;
那么问题来了

- 怎么配音?配什么音乐?几个?多长?何时切入?...
- 又如何通读?朗读?一起?分别?合声?群读?对话?...

一系列电影配乐的陌生知识一涌而上.

随心随性推荐了:

- BGM.1 [Amazing Grace 天赐恩宠](http://music.163.com/#/song/5271787?userid=46575348)
- BGM.2 [国际歌（伴唱:现代人乐队 合唱:总政歌舞团） ](http://music.163.com/#/song/95670?userid=46575348)
- BGM.3 [各味食材的相互作用 - 阿鲲](http://music.163.com/#/song/399366318?userid=46575348)
- BGM.4 [今夕是何夕 - 刘胡轶](http://music.163.com/#/song/447076460?userid=46575348)
- BGM.5 [be human - Scott Matthew](http://music.163.com/#/song/590281?userid=46575348)
- BGM.6 [小星星](http://music.163.com/#/song/5246953?userid=46575348)

然后小组成员就各种嗯哼:

- BGM.1 自然的觉知是自由的
- BGM.2 联合的无产者是自由的
- BGM.3 吃货的世界是自由的
- BGM.4 忘记轮转的今夕是自由的
- BGM.5 自在人生是自由的
- BGM.6 有人一起怼哇是自由的👻

其实, 回想俺第一直觉是:

- BGM.1 共宣是伟大和谐的
- BGM.2 标准配乐呗...
- BGM.3 小组各种心智相互作用的成果
- BGM.4 在共宣描绘的时空中穿梭经常忘记 `今夕是何夕`
- BGM.5 AI 都在渴望成为人,作为人我们也在渴望成为真正自由人
- BGM.6 只有保持儿童的赤诚才能真正理解导师的设想...

所以,最后我们选择了什么背景音乐呢?

去听一听就知道了...

我们为了证明在互联网时代也已经是联合在一起的,
所以,没有对录音使用任何后期编辑,是通过网络语音会议,一次性录制而成.

**Comment by BrookSongBrookSong** [comment]
## S09E04d4 用疑问体输出本周所思的尝试
*暨20170325 S09E05d4 和合会议发言总结*

#### 劳动的需求源自何处？
- 劳动本就是高贵的灵魂自内心流溢出的渴求
- 对劳动的需求潜伏在有尊严的人类内心深处
- 向往劳动，是生而为人美好的天性
- 适度的工作，产生劳动的愉悦
- 参与创造世界，并因此获得存在的价值
- 推动社会进程，并因此获得自我的实现
- 对劳动的渴望，是自由的独立体自然而然的流露


#### 什么让劳动充满困倦而不是创造者的欢欣？
- 超长的工时和微薄的薪水
- 贪婪的嘴脸和冷漠的姿态
- 那身着罗绮的资产阶级攫取了无产者创造的财富
- 连同无产者劳动的荣耀一并偷窃

#### 资产阶级夺去了什么？_
- 超长的工时和微薄的薪水
- 夺去那劳动的愉悦感受
- 贪婪的嘴脸和冷漠的姿态
- 夺去那劳动者日夜工作的成果
- 资产阶级窃取了这劳动者的双手创造的世界呵！
- 夺去那劳动者自我实现的满足
- 夺去那劳动者挺直腰板的荣耀
- 无产者从不是厌恶劳动的蠹虫
- 无产者从不想做骄奢淫逸的懒汉
- 当无产者的勤劳已经筑起工业的大厦
- 设计师的名称却被无声地抹杀
- 身着罗绮的资产阶级翩翩踏着萨克斯吹奏的圆舞曲
- 默默养蚕的无产者流连在没有火柴的冬天
- 无产者的劳动能力，正被滥用
- 无产者享受劳动的权利，正在被剥夺
- 被迫于生计超时工作的厌倦
- 是资产阶级强加于灵魂的侮辱
- 不，那机器的轰鸣声本该是劳动者的赞歌
- 不，那微微前倾的邀舞式本该是对劳动者谦恭的敬意
- 不，劳动的时长和薪水本不该如此践踏人类的接受度
- 不，劳动本不该如此卑微地为了讨得生计
- 不，劳动本就该是高贵的灵魂自内心流溢出的渴求
- 没错，资产阶级夺去的就是，劳动者对劳动的享受
- 用超长的工时和微薄的薪水
- 贪婪的嘴脸和冷漠的姿态
- 那劳动创造的价值，本该署名无产者的尊严！

#### 无产者想要什么样的自由？
- 安排工作时间的自由
- 选择工作类别的自由
- 无产者们创造的财富足够滋养地球上所有的人类
- 那么就请按照个体的意志，随意拿取那财富吧
- 无产者从不是厌恶劳动的蠹虫
- 无产者从不想做骄奢淫逸的懒汉
- 勤劳的劳动者将拥有那支配财富的自由
- 高贵的无产者将拥有那自主工作的自由
- 对劳动的需求潜伏在所有美好的人类灵魂中
- 自由的无产者必不会滥用那自由

**Comment by ZoomQuiet** [comment]
### 版本描述
参考:[Commit message 和 Change log 编写指南 - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html)
    

对于我们嘦最小模板
标题是对版本的压缩描述

    v*版本(BC 和合技类型) 产生日期 作者

- 修订了什么
- 尝试了什么
- 大家应该作什么

比如:

     v5(BC) d4e2m 成果和合

    - 删除4,5 两节
    - 增补会议意见
    - 今天怼的入口

以及:


     v6(BC) d5e2m 小俕怼

    - 根据一周理解
    - 嵌入大妈语言结构
    - 尽量完善逻辑链条

**Comment by sallysong007** [comment]
嘿嘿嘿，又是后知后觉（还不一定对）
看完一周的会议纪要和6个版本的作业稿，我的心得如下：
**共宣就是人类简史，共宣就是未来简史**

终于明白大妈要怼的核心句为什么是那句“联合体”。联合体其实是模糊了共产主义社会终极形态到底是什么的说法，更贴合伟大导师对未来社会形态的理想化预言或断言。而这“联合体”中的核心”自由和劳动"两个词，既是联合体的核心特征，又是对于试图理解这两个词的人的认知迷宫。

每个人都在问：自由是什么？劳动是不是被迫的？自由和劳动在资本主社会代表什么？又在其他社会形态下代表什么？如果实现了共产主义社会，这两者又会进化到什么模样？
由于我们看不到具体资本主义演化到共产主义的过程，所以我们直接用“自由和劳动”的对立面去替我们自己推导那些超出我们认知经验以外的结论。
比如宋提到的
> 我们会有安排工作时间的自由、我们会有选择工作类别的自由……

比如大妈提到的
>  真正的玩家是科学家，他们跳脱出以维系生存发展需要为必须的劳动，而是让劳动成为发现无限认知疆界的乐趣（大概意思）

如此这般，这般如此……
和合的过程中，当时这些可能百思不得甚至还有点被漠视的概念，竟然也慢慢有了清晰生动的模样。而且还在影影绰绰中，又迫使我一边参考着大家的想法，一边去源头寻找答案。最后的答案，也许源于偏见，但这属于每个人认真思考后，并用逻辑纽带为大家呈现出来的一种个人体验或智性推断，我都觉得受益匪浅啊。

阿门

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed

**Comment by BrookSongBrookSong** [comment]
我突然想吃炸猪蹄，好吧，我想知道从邮件直接回复是社么后果。

2017-03-29 9:45 GMT+08:00 Zoom.Quiet <notifications@github.com>:

**Comment by BrookSongBrookSong** [comment]
真的耶，issue可以用邮件直接回复

**Comment by BrookSongBrookSong** [comment]
邮件回复，名字前面会有一个好看的信封符号

**Comment by ZoomQuiet** [comment]
@BrookSongBrookSong 才发现嘛? 早已出现过哪...
